webhook_url = "https://discordapp.com/api/webhooks/1506181559332634624/lUW2_ZVIqhcwMHipf0VLx4zca0LUuUjru1IeEHnbg4rwhNzv5nB3JZDPZHlaX88fP1ZL"

[stores]
zip_code = ""
stores = [
    "R119",
    "R111",
    "R711"
]

[devices]
models = [
    "MG854J/A",
    "MG864J/A",
    "MG874J/A",
    "MG894J/A",
    "MG8A4J/A",
    "MG8C4J/A"
]

[telegram]
api_id = 123456
api_hash = "dummy_hash"
bot_token = "dummy_token"
chat_id = "dummy_chat_id"
